var LAUNCHPAD_LIBRARY = {
  supervisor: {
    key: 'supervisor',
    label: 'Supervisor Launchpad',
    subtitle: 'Live tools for oversight, review, triage, and team coordination.',
    intro: 'This view keeps the live tools supervisors use most in one place, with a plain-English reminder of what each project does and when to use it.',
    projects: [
      {
        name: 'Delinquency Command Center',
        roles: ['shared', 'supervisor'],
        sort: 10,
        pinned: true,
        summary: 'Review delinquency across the portfolio and spot urgent accounts quickly.',
        use: 'Use when you need a territory-level delinquency scan or need to find accounts that require follow-up.',
      },
      {
        name: 'Property Management Board (PMB)',
        roles: ['shared', 'supervisor'],
        sort: 20,
        pinned: true,
        summary: 'High-level portfolio operations board for management workflow and oversight.',
        use: 'Use when you want a broad operational view instead of jumping directly into a single property tool.',
      },
      {
        name: 'Vacancy Dashboard',
        roles: ['shared', 'supervisor'],
        sort: 30,
        pinned: true,
        summary: 'Track occupied and vacant status across the portfolio in one live view.',
        use: 'Use to see where vacancies are clustering and which properties need attention first.',
      },
      {
        name: 'Team Tasks',
        roles: ['shared', 'supervisor'],
        sort: 40,
        summary: 'Shared task coordination and follow-up board for the team.',
        use: 'Use to assign, review, or resume team tasks without hunting through notes.',
      },
      {
        name: 'Check Auditor',
        roles: ['supervisor'],
        sort: 50,
        summary: 'Audit checks and flag setup gaps before they become bigger problems.',
        use: 'Use when you want to review checks, exceptions, and anything that still needs a human eye.',
      },
      {
        name: 'New Hire Intro Builder',
        roles: ['supervisor'],
        sort: 60,
        summary: 'Build or refresh onboarding guidance for a new team member.',
        use: 'Use when someone is starting and you want a clean intro path instead of piecing things together by hand.',
      },
      {
        name: 'Owner Specific Dashboard',
        roles: ['shared', 'supervisor'],
        sort: 70,
        summary: 'Focused owner-level dashboard for targeted portfolio review.',
        use: 'Use when you need a narrow owner view rather than a broad portfolio scan.',
      },
      {
        name: 'Prospect Communication Dashboard',
        roles: ['supervisor'],
        sort: 80,
        summary: 'Track prospect communication and follow-up status.',
        use: 'Use to keep outreach organized and visible when prospect work is active.',
      },
      {
        name: 'Ice Breakers',
        roles: ['supervisor'],
        sort: 90,
        summary: 'Conversation starters and team prompts.',
        use: 'Use when you want quick prompts for meetings, training, or support conversations.',
      }
    ]
  },
  propertyManager: {
    key: 'propertyManager',
    label: 'Property Manager Launchpad',
    subtitle: 'Live tools for property-level operations and resident-facing workflows.',
    intro: 'This view keeps the live tools property managers use most in one place, with clear purpose notes and a lighter, menu-style layout.',
    projects: [
      {
        name: 'Owner Directory',
        roles: ['shared', 'property-manager'],
        sort: 10,
        pinned: true,
        summary: 'Look up owners, property ownership, and contact details quickly.',
        use: 'Use when you need owner contact information or ownership context for a property.',
      },
      {
        name: 'Property Directory',
        roles: ['shared', 'property-manager'],
        sort: 20,
        pinned: true,
        summary: 'Property-level setup, fees, reserves, and contract details.',
        use: 'Use when you need property setup details, fee settings, or reserve information.',
      },
      {
        name: 'Vacancy Dashboard',
        roles: ['shared', 'property-manager'],
        sort: 30,
        pinned: true,
        summary: 'See occupied and vacant status across the portfolio.',
        use: 'Use to spot vacant units and check which properties need immediate follow-up.',
      },
      {
        name: 'Make Ready Board',
        roles: ['shared', 'property-manager'],
        sort: 40,
        pinned: true,
        summary: 'Track turn work and readiness before a unit goes back to market.',
        use: 'Use when a unit is in turn and you need to see readiness at a glance.',
      },
      {
        name: 'Notice To Vacate (Forms)',
        roles: ['property-manager'],
        sort: 50,
        summary: 'Prepare and send move-out notices from a guided form flow.',
        use: 'Use when a notice to vacate needs to be prepared without starting from scratch.',
      },
      {
        name: 'Vacancy Tracker',
        roles: ['property-manager'],
        sort: 60,
        summary: 'Track individual vacancies and follow-up items.',
        use: 'Use when you want a detailed vacancy-by-vacancy follow-up list.',
      },
      {
        name: 'Leasing Fee Audit',
        roles: ['property-manager'],
        sort: 70,
        summary: 'Review leasing fee calculations and catch missing charges.',
        use: 'Use to check leasing-related billing and make sure fees are being captured correctly.',
      },
      {
        name: 'Utility Bill Back Tool',
        roles: ['property-manager'],
        sort: 80,
        summary: 'Allocate utility charges back to residents or properties.',
        use: 'Use when utilities need to be assigned or backed out in a clean, repeatable way.',
      },
      {
        name: 'Demand Generator',
        roles: ['property-manager'],
        sort: 90,
        summary: 'Support vacancy and marketing demand planning.',
        use: 'Use when you need to review demand, push follow-up, or plan for marketing activity.',
      },
      {
        name: 'Tenant Action Sheet',
        roles: ['property-manager'],
        sort: 100,
        summary: 'Manage tenant-side action items and follow-ups.',
        use: 'Use when you need a simple list of tenant actions that still need attention.',
      },
      {
        name: 'Utility Tracker 360',
        roles: ['shared', 'property-manager'],
        sort: 110,
        summary: 'Follow utility charges and related status across the portfolio.',
        use: 'Use when utility-related tracking needs a broader live view.',
      },
      {
        name: 'Key Inventory Database (KID)',
        roles: ['property-manager'],
        sort: 120,
        summary: 'Track key assignments and returns.',
        use: 'Use when you need to see who has what key and what still needs to come back.',
      },
      {
        name: 'Fitz Make Ready Board',
        roles: ['property-manager'],
        sort: 130,
        summary: 'Property-specific make-ready tracking for Fitz.',
        use: 'Use when Fitz turn work needs a focused make-ready view.',
      }
    ]
  }
};
