/**
 * PROJECT REGISTRY - Canonical configuration for PropAlliance Hub
 * Merged from admin-hub-dev and recovered Workshop registry.
 * Local preparation only until pushed/deployed intentionally.
 */

function getProjectRegistry() {
  return [
    {
        "id": "PropAlliance_Hub",
        "title": "PropAlliance Hub",
        "icon": "🛡️",
        "scriptId": "14s3xyW1nkk43905FZ4ABIuk8Xsi6Rt7DeDB3AYoHTp9V4Oq8Q6UJplVf",
        "liveUrl": "https://script.google.com/macros/s/AKfycbyogm2uig9R05iBjeI976boZzrgRJJ3yiLbWoMXdhYjLoAn5hfoE5Es2waXpuI3aSOsxg/exec",
        "group": "core",
        "desc": "Official launch/control center and current authoritative Hub experience.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "testScriptId": "14s3xyW1nkk43905FZ4ABIuk8Xsi6Rt7DeDB3AYoHTp9V4Oq8Q6UJplVf",
        "testEditorUrl": "https://script.google.com/d/14s3xyW1nkk43905FZ4ABIuk8Xsi6Rt7DeDB3AYoHTp9V4Oq8Q6UJplVf/edit",
        "testLiveUrl": "https://script.google.com/macros/s/AKfycbzy8ZjiCKk_0SJgPHTXmPkzrhFyAVjlqg6gL7HAwbsF/exec",
        "testStatus": "Exists",
        "editorUrl": "https://script.google.com/d/14s3xyW1nkk43905FZ4ABIuk8Xsi6Rt7DeDB3AYoHTp9V4Oq8Q6UJplVf/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/PropAlliance_Hub",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/PropAlliance_Hub/PROJECT_MANIFEST.json",
        "migrationStatus": "hub_api_primary",
        "dataMode": "hub_api",
        "hubTargets": [],
        "needsApiConversion": false,
        "credentialReviewNeeded": true,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "The_Workshop",
        "title": "The Workshop",
        "icon": "🛠",
        "scriptId": "1lVDvYwIJro89eVJrPgNhiHyrZlQkRSxR49URl3TfcixanrHUrhsXniH-",
        "liveUrl": "https://script.google.com/a/macros/propalliance.com/s/AKfycbzwArfpLNQnQIOgwuBKFeeCbdmc4m39kksuNL7TDF6_ljgGKdGoHgOGbEWuku8jbAdZag/exec",
        "group": "core",
        "desc": "The central engine for all Property Alliance tools.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "testScriptId": "13qabzaIGfoj5P2XymYTfTNKOPBUt0R4-btvf5ljvMAic3hx_4bxEnI09",
        "testEditorUrl": "https://script.google.com/d/13qabzaIGfoj5P2XymYTfTNKOPBUt0R4-btvf5ljvMAic3hx_4bxEnI09/edit",
        "testLiveUrl": "https://script.google.com/macros/s/AKfycbxwxzCFxdtNdjL9hqIVjS7ilVshSbVP4Pcu1wBGk1tIfJ1SFQDDBKgBUeCV4bpBR_9c9A/exec",
        "testStatus": "Exists",
        "editorUrl": "https://script.google.com/d/1lVDvYwIJro89eVJrPgNhiHyrZlQkRSxR49URl3TfcixanrHUrhsXniH-/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/The_Workshop",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/The_Workshop/PROJECT_MANIFEST.json",
        "migrationStatus": "legacy_csv_or_drive_data_needs_conversion",
        "dataMode": "legacy_csv_email_or_drive",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": true,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Delinquency_Command_Center",
        "title": "Delinquency Command Center (DCC)",
        "icon": "📉",
        "scriptId": "13IIWcmpOPXqW1SzMwZDdjp_8BQ31Ln6eU72hQf8qBMGKALuameT4Qyja",
        "liveUrl": "https://script.google.com/a/macros/propalliance.com/s/AKfycbzSkOcikJBs2lhFT7tMfimlPz2cveEJxTxiBhxtJ8N4zowZV2BDwyv5r_QMnc1YFKMW/exec",
        "group": "core",
        "desc": "Risk prioritization and delinquency tracking engine.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "testScriptId": "1KaNAACPY37-MceLRlwS3sGEpdCh6KptrbACX-M80r-W4I8lZ6xM-K73P",
        "testEditorUrl": "https://script.google.com/d/1KaNAACPY37-MceLRlwS3sGEpdCh6KptrbACX-M80r-W4I8lZ6xM-K73P/edit",
        "testLiveUrl": "https://script.google.com/macros/s/AKfycbyRzPLMDSsnHvTlJ9O4Wkf2msW6SVbmFD_jGk5pJbBE97rOFxR1U3BUMB0VpdSORv32/exec",
        "testStatus": "Exists",
        "editorUrl": "https://script.google.com/d/13IIWcmpOPXqW1SzMwZDdjp_8BQ31Ln6eU72hQf8qBMGKALuameT4Qyja/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/DCC",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/DCC/PROJECT_MANIFEST.json",
        "migrationStatus": "api_wired",
        "dataMode": "direct_appfolio_api_or_mixed",
        "hubTargets": [
            "delinquency",
            "properties"
        ],
        "needsApiConversion": false,
        "credentialReviewNeeded": true,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Tenant_Action_Sheet",
        "title": "Tenant Action Sheet",
        "icon": "📝",
        "scriptId": "10v5juYvhkGSINGFlezHOvb3m2ilNTzzRUUC8Ly10cDKoYmb-TJugjZJS",
        "liveUrl": "https://script.google.com/macros/s/AKfycbyF67VFCc-siiKUGnLBe_bA5uDgVH2pH3bz0Zo1N0d6rfKF5417j3-mGZxrQqN8hIbb/exec",
        "group": "core",
        "desc": "Workflow for new/renewal leases and roommate splits.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/1v8k4AqCj3ZEkKEOzH5wBDpzqrOL2wpeAx1weAf5ETQ-nglQgVdPZAm0X/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Tenant_Action_Sheet",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Tenant_Action_Sheet/PROJECT_MANIFEST.json",
        "migrationStatus": "legacy_csv_or_drive_data_needs_conversion",
        "dataMode": "legacy_csv_email_or_drive",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": true,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Property_Dashboard",
        "title": "Property Management Board (PMB)",
        "icon": "🌐",
        "scriptId": "1rnQEXxDoEfmkBtZ3_08t36UsIF8BlCB5uBhXXIwdpPA3UEenLkNZH7_v",
        "liveUrl": "https://script.google.com/macros/s/AKfycbztHwLDlcs3aw1X5OV7U5sYNV-uua0ihza4Fx_oweCFf2xrW2vsM2Tj9JA6rQ0lNyuVbA/exec",
        "group": "core",
        "desc": "Operational KPI dashboard and property overview.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "testScriptId": "1740B0Y7ZFOqyl6paMZ-DbZjLWiXL1mZd9aWjWv3QR4rcPoonhbB155rN",
        "testEditorUrl": "https://script.google.com/d/1740B0Y7ZFOqyl6paMZ-DbZjLWiXL1mZd9aWjWv3QR4rcPoonhbB155rN/edit",
        "testLiveUrl": "https://script.google.com/macros/s/AKfycbzlNXHauVXO6ycCgflXIOCv3aaspO2B3zQx5u5dchY4_3PDzwHtL148mN-rHWti2-HMuA/exec",
        "testStatus": "Exists",
        "editorUrl": "https://script.google.com/d/1rnQEXxDoEfmkBtZ3_08t36UsIF8BlCB5uBhXXIwdpPA3UEenLkNZH7_v/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Property_Dashboard",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Property_Dashboard/PROJECT_MANIFEST.json",
        "migrationStatus": "partial_hub_api_needs_finish",
        "dataMode": "hub_api",
        "hubTargets": [
            "pmb"
        ],
        "needsApiConversion": true,
        "credentialReviewNeeded": true,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Make_Ready_Board",
        "title": "Make Ready Board",
        "icon": "🧰",
        "scriptId": "1U1a-mOo995GvSqj3Ifhp44Rl0ZVdtWgF8VRzHo3DyZiLqgKGCmyyxOMH",
        "liveUrl": "https://script.google.com/macros/s/AKfycbziipKaKwwdxEjwBBdnAVnqI788YLtsmmxgBKl43vLjDEJnpu2Y4lD3AMajPmGo_n2Q/exec",
        "group": "core",
        "desc": "Unit turnover and maintenance workflow manager.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "testScriptId": "18kd-t6JXFRfcjyc_S8R0aXxIMqy2HQgy6jXq3FISJHtd-IT0-xTUnBVK",
        "testEditorUrl": "https://script.google.com/d/18kd-t6JXFRfcjyc_S8R0aXxIMqy2HQgy6jXq3FISJHtd-IT0-xTUnBVK/edit",
        "testLiveUrl": "https://script.google.com/macros/s/AKfycbxawqmyyg1aQ1nbL5-oIqO80j3fqCgjQNWExEry8lF9ROLPudL-hLemkCsWsu6zaJ8k/exec",
        "testStatus": "Exists",
        "editorUrl": "https://script.google.com/d/1U1a-mOo995GvSqj3Ifhp44Rl0ZVdtWgF8VRzHo3DyZiLqgKGCmyyxOMH/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Make_Ready_Board",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Make_Ready_Board/PROJECT_MANIFEST.json",
        "migrationStatus": "hub_api_present_needs_verification",
        "dataMode": "hub_api",
        "hubTargets": [
            "vacancies",
            "moveouts",
            "inspections",
            "workorders"
        ],
        "needsApiConversion": true,
        "credentialReviewNeeded": true,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Utility_Bill_Audit",
        "title": "Utility Bill Back Tool",
        "icon": "💰",
        "scriptId": "1-fwIEM4RQXr0SL2AaAgwhLA-ElWLdwwWaTTVvq_cId6qr1Phzw8fHFWG",
        "liveUrl": "https://script.google.com/macros/s/AKfycbwSXLgSHXM7Xup1xqaKMS1hMKNc3VlQ3YAWaAhyEl7z52MLjD1x1HEGqwWtaK99kqrm/exec",
        "group": "core",
        "desc": "Financial auditing for utility bill-back accuracy.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "testScriptId": "1iJCI54zX6hrWbW_XDDIoYxydp8R_uUzwgI5VLzvGl0UNpK7qjOR856yT",
        "testEditorUrl": "https://script.google.com/d/1iJCI54zX6hrWbW_XDDIoYxydp8R_uUzwgI5VLzvGl0UNpK7qjOR856yT/edit",
        "testLiveUrl": "https://script.google.com/macros/s/AKfycbz0R4h3tqzDp7xHL9zY3h7Y3KO6FlU6KiTaBno72sfUdyEdBP9qEDHgd2eIwvPVcaDp/exec",
        "testStatus": "Exists",
        "editorUrl": "https://script.google.com/d/1-fwIEM4RQXr0SL2AaAgwhLA-ElWLdwwWaTTVvq_cId6qr1Phzw8fHFWG/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Utility_Bill_Audit",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Utility_Bill_Audit/PROJECT_MANIFEST.json",
        "migrationStatus": "legacy_csv_or_drive_data_needs_conversion",
        "dataMode": "legacy_csv_email_or_drive",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Team_Tasks",
        "title": "Team Tasks",
        "icon": "✅",
        "scriptId": "1p-vccvA--EU-T3gpGkfPy0Nn6jh6wNFeQ6iO4L5UmUbbXNofjXDMJlBO",
        "liveUrl": "https://script.google.com/macros/s/AKfycbwcA09bxJbxlfNDImdUomtJ9BXhg-zMCa9K5BykTFutLw2Wm1l6CiqMDD5JLAluVEt3dg/exec",
        "group": "core",
        "desc": "Daily action tracking and accountability system.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "testScriptId": "1RXRxq7nCvTN5pPFRaLuH0H29Q88_RMiO5lD7tlGUuAdd5Ah8jhVDNZf5",
        "testEditorUrl": "https://script.google.com/d/1RXRxq7nCvTN5pPFRaLuH0H29Q88_RMiO5lD7tlGUuAdd5Ah8jhVDNZf5/edit",
        "testLiveUrl": "https://script.google.com/macros/s/AKfycbztTvystTVB4w8hcNjBVCy8RWrQVJTv-DGR_zcJi5JAf8WZjMlszbfwLOHkJiHwzTh_/exec",
        "testStatus": "Exists"
    },
    {
        "id": "Utility_Tracker_360",
        "title": "Utility Tracker 360",
        "icon": "⚡️",
        "scriptId": "1-2ZLfJ0lP7VDdG4U4fK7hQyTpS_fjbC8OcTQhH07G8TDv7_R9CxN1RRs",
        "liveUrl": "https://docs.google.com/spreadsheets/d/14kGAQbX5m4qWPgkUJGPlZ08dIftOw23eRRdHb7H1QEQ/edit",
        "group": "core",
        "desc": "Next-gen utility ingestion and matching engine.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null
    },
    {
        "id": "NoticeToVacate_Automation",
        "title": "Notice To Vacate - Manual Generation",
        "icon": "📄",
        "scriptId": "1vqLnZ3k-98asa1-CR2vShpUnrwBA3I3C7UzC6Fjq8x4C3acnnRB2d0h2",
        "liveUrl": "https://script.google.com/macros/s/AKfycby0VeAikBLnTNfxVrSA5XZEw8oMQ9zs_qLM9RutcBPtYlg6qJF4Z5eAORLdyJop4U6a6A/exec",
        "group": "core",
        "desc": "Automation engine for processing resident terminations.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/1vqLnZ3k-98asa1-CR2vShpUnrwBA3I3C7UzC6Fjq8x4C3acnnRB2d0h2/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/NoticeToVacate_Automation",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/NoticeToVacate_Automation/PROJECT_MANIFEST.json",
        "migrationStatus": "needs_inventory",
        "dataMode": "unknown",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Vacancy_Tracker",
        "title": "Vacancy Tracker",
        "icon": "📈",
        "scriptId": "1rTqwtcB0ylvWZlsGeAIFf56frVGCbYOr6k6RP8-2d1QEwrxdGT2U8C1y",
        "liveUrl": "https://script.google.com/macros/s/AKfycbwXplNgWrue4ZmGTtWCUrRPwKeX20f8CZV9RbkICe1TYdUpBS_A4t6Qsi1ano__ZFL2Lg/exec",
        "group": "core",
        "desc": "Real-time feed from daily vacancy email reports.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/1rTqwtcB0ylvWZlsGeAIFf56frVGCbYOr6k6RP8-2d1QEwrxdGT2U8C1y/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Vacancy_Tracker",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Vacancy_Tracker/PROJECT_MANIFEST.json",
        "migrationStatus": "legacy_csv_email_needs_conversion",
        "dataMode": "legacy_csv_email_or_drive",
        "hubTargets": [
            "vacancies"
        ],
        "needsApiConversion": true,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Alias_Database",
        "title": "Alias Database",
        "icon": "📂",
        "scriptId": "1Gm-QqMztoM3B6OIuji-kTtl-2c8foOfq5XQ58FoZ8mC5T_4sGWtxxdeB",
        "liveUrl": null,
        "group": "beta",
        "desc": "Canonical property identity mapping so a property like 13MOL1380 and 14MOL1380 can be treated as the same real property for historical tracking while still preserving territory-specific reporting.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/1Gm-QqMztoM3B6OIuji-kTtl-2c8foOfq5XQ58FoZ8mC5T_4sGWtxxdeB/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Alias_Database",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Alias_Database/PROJECT_MANIFEST.json",
        "migrationStatus": "needs_inventory",
        "dataMode": "unknown",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "NoticeToVacate_Automation_Pull",
        "title": "Notice To Vacate (Forms)",
        "icon": "📝",
        "scriptId": "15aneGBzgMZew1T55N8mKwaWTel17NOCP2gdbJjGqknObqKfnedrQExWo",
        "liveUrl": null,
        "group": "beta",
        "type": "resource",
        "desc": "Provide team members a way to send the correct NTV form link to a tenant based on territory.",
        "resourceLinks": [
            {
                "label": "Aurora",
                "url": "https://script.google.com/macros/s/AKfycby0VeAikBLnTNfxVrSA5XZEw8oMQ9zs_qLM9RutcBPtYlg6qJF4Z5eAORLdyJop4U6a6A/exec?region=aurora"
            },
            {
                "label": "Denver Central",
                "url": "https://script.google.com/macros/s/AKfycby0VeAikBLnTNfxVrSA5XZEw8oMQ9zs_qLM9RutcBPtYlg6qJF4Z5eAORLdyJop4U6a6A/exec?region=denver"
            },
            {
                "label": "Colorado Springs",
                "url": "https://script.google.com/macros/s/AKfycby0VeAikBLnTNfxVrSA5XZEw8oMQ9zs_qLM9RutcBPtYlg6qJF4Z5eAORLdyJop4U6a6A/exec?region=coloradosprings"
            },
            {
                "label": "OKC",
                "url": "https://script.google.com/macros/s/AKfycby0VeAikBLnTNfxVrSA5XZEw8oMQ9zs_qLM9RutcBPtYlg6qJF4Z5eAORLdyJop4U6a6A/exec?region=okc"
            },
            {
                "label": "Fitz",
                "url": "https://script.google.com/macros/s/AKfycby0VeAikBLnTNfxVrSA5XZEw8oMQ9zs_qLM9RutcBPtYlg6qJF4Z5eAORLdyJop4U6a6A/exec?region=fitz"
            },
            {
                "label": "GL / VV",
                "url": "https://script.google.com/macros/s/AKfycby0VeAikBLnTNfxVrSA5XZEw8oMQ9zs_qLM9RutcBPtYlg6qJF4Z5eAORLdyJop4U6a6A/exec?region=glvv"
            }
        ],
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/15aneGBzgMZew1T55N8mKwaWTel17NOCP2gdbJjGqknObqKfnedrQExWo/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/NoticeToVacate_Automation_Pull",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/NoticeToVacate_Automation_Pull/PROJECT_MANIFEST.json",
        "migrationStatus": "needs_inventory",
        "dataMode": "unknown",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Vacancy_Dashboard",
        "title": "Vacancy Dashboard",
        "icon": "📊",
        "scriptId": "19sH9JmoilAPJDyGfF5q8VJJU-u9kxXyi5nVbr1Zc7nltevumoJLZC9ci",
        "liveUrl": null,
        "group": "beta",
        "desc": "Beta: Management overview of current vacancy trends. (Unresolved Placeholder)",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/19sH9JmoilAPJDyGfF5q8VJJU-u9kxXyi5nVbr1Zc7nltevumoJLZC9ci/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Vacancy_Dashboard",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Vacancy_Dashboard/PROJECT_MANIFEST.json",
        "migrationStatus": "hub_api_migrated",
        "dataMode": "hub_api",
        "hubTargets": [
            "vacancies"
        ],
        "needsApiConversion": false,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Vacancy_Operations_System",
        "title": "Vacancy Operations System",
        "icon": "🏠",
        "scriptId": "1oRBGrUeMPZoqY_AbNPa_R7zprsxALRgJJHRddgB588wG4hkI0Rz6bWxF",
        "liveUrl": "https://script.google.com/a/macros/propalliance.com/s/AKfycbyLlhh3ciO0xeA_WEDLhZwQUxtKAYtj_f2cJRNXCwEpfc_uZGJJA5pBwlBHr0xiTgh3tQ/exec",
        "devUrl": "https://script.google.com/a/macros/propalliance.com/s/AKfycbx3CP9NhKYItHroaWsQUXIcH_v8fny7K4QBQVYTDoiW/dev",
        "group": "core",
        "desc": "Operational command center for vacancy lifecycle, make-ready, marketing, and leasing progress.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/1oRBGrUeMPZoqY_AbNPa_R7zprsxALRgJJHRddgB588wG4hkI0Rz6bWxF/edit",
        "devScriptUrl": "https://script.google.com/d/1oRBGrUeMPZoqY_AbNPa_R7zprsxALRgJJHRddgB588wG4hkI0Rz6bWxF/edit",
        "driveFolderLocalPath": "/Users/richgreen/Dev/PA-Registry-DEV-Workspaces/vacancy-operations-system/src",
        "manifestLocalPath": "/Users/richgreen/Dev/PA-Registry-DEV-Workspaces/vacancy-operations-system/registry.json",
        "migrationStatus": "dev_added_to_registry",
        "dataMode": "direct_appfolio_api_or_mixed",
        "hubTargets": [
            "vacancies",
            "make_ready",
            "leasing"
        ],
        "needsApiConversion": false,
        "credentialReviewNeeded": true,
        "lastMigrationInventoryUpdate": "2026-05-26T00:00:00"
    },
    {
        "id": "Official_Marketing_Rediness_Command_Center",
        "title": "Marketing Readiness Checklist",
        "icon": "📊",
        "scriptId": "1pR3y800ZLbJdmLXnsJPrdzYcG6tRSuzceZHmuvSCDeM2gF7_UTMb5gum",
        "liveUrl": "https://script.google.com/macros/s/AKfycbw71YExtpD3Ts225u1zbxg9DhFn52anNeG5OJ2-R644irnSsZ6dj8D7Exb7RReyvGFP/exec",
        "group": "admin_tools",
        "desc": "Comprehensive audit for marketing and photo quality.",
        "testScriptId": "1rCwGx5JvyFw65RzZ8Brja3Z8pandm0XMB7RCDOWJ8eV664Xy7RUG584R",
        "testEditorUrl": "https://script.google.com/d/1rCwGx5JvyFw65RzZ8Brja3Z8pandm0XMB7RCDOWJ8eV664Xy7RUG584R/edit",
        "testLiveUrl": "https://script.google.com/macros/s/AKfycbxp83ibCjyebosxBPMbcRzB2Pd6AztnnSpEdcN-5DY9PpxXQnZ7fTS8XMx284s80kS5ew/exec",
        "testStatus": "Exists",
        "editorUrl": "https://script.google.com/d/1pR3y800ZLbJdmLXnsJPrdzYcG6tRSuzceZHmuvSCDeM2gF7_UTMb5gum/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/MRC",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/MRC/PROJECT_MANIFEST.json",
        "migrationStatus": "api_wired_with_legacy_fallback",
        "dataMode": "direct_appfolio_api_or_mixed",
        "hubTargets": [
            "mrc",
            "unit_vacancy",
            "unit_directory"
        ],
        "needsApiConversion": false,
        "credentialReviewNeeded": true,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Owner_Directory",
        "title": "Owner Directory",
        "icon": "📒",
        "scriptId": "1e3u2luxnbdkGGpx90hkIimE-42ux-S90gMl65_URfpIyS5u-mf8b_6nm",
        "liveUrl": "https://script.google.com/macros/s/AKfycbzB31GfdQiij6bLX1OhrC1vUTYyZDznvqb4Tv1jOD-UrVC5wNOjUCl2QHhQwVYhB7TxDw/exec",
        "group": "admin_tools",
        "desc": "Contact and management details for asset owners.",
        "editorUrl": "https://script.google.com/d/1e3u2luxnbdkGGpx90hkIimE-42ux-S90gMl65_URfpIyS5u-mf8b_6nm/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Owner_Directory",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Owner_Directory/PROJECT_MANIFEST.json",
        "migrationStatus": "hub_api_migrated",
        "dataMode": "hub_api",
        "hubTargets": [
            "all"
        ],
        "needsApiConversion": false,
        "credentialReviewNeeded": true,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "New_Hire_Intro_Builder",
        "title": "New Hire Intro Builder",
        "icon": "✨",
        "scriptId": "14SxalHP6fQW7D_-lgI5H110NlXAPDdV0lVpJmzHBk-j8U7MUe_FXqIef",
        "liveUrl": "https://script.google.com/macros/s/AKfycbwig8XPh6uF5teEMRV04dM1Nyea_cq7feNpcIzuq10CzECtKhQ25qece0zLbdRQqbUK/exec",
        "group": "admin_tools",
        "desc": "Training and onboarding guide for new team members.",
        "editorUrl": "https://script.google.com/d/14SxalHP6fQW7D_-lgI5H110NlXAPDdV0lVpJmzHBk-j8U7MUe_FXqIef/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/New_Hire_Intro_Builder",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/New_Hire_Intro_Builder/PROJECT_MANIFEST.json",
        "migrationStatus": "needs_inventory",
        "dataMode": "unknown",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "VacancyScope",
        "title": "Vacancy Scope",
        "icon": "🏠",
        "scriptId": "1ABPzIMhMJ72blESEjrhPGVtvq53PI1JzolL1rpyEwIeq5SBvfus_WhdZ",
        "liveUrl": "https://script.google.com/macros/s/AKfycbxjr2zZlEzAeCga69Ylp0w2LlVpb2ZSwqR0vcHaxQelWd02yaH5E2oEbvJGiDCndbRUQg/exec",
        "group": "admin_tools",
        "desc": "Quality control for unit marketing and listing readiness.",
        "editorUrl": "https://script.google.com/d/1ABPzIMhMJ72blESEjrhPGVtvq53PI1JzolL1rpyEwIeq5SBvfus_WhdZ/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/VacancyScope",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/VacancyScope/PROJECT_MANIFEST.json",
        "migrationStatus": "hub_api_migrated",
        "dataMode": "hub_api",
        "hubTargets": [
            "vacancies"
        ],
        "needsApiConversion": false,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Property_Directory",
        "title": "Property Directory",
        "icon": "🏢",
        "scriptId": "1aeyESH70zD4a6_AGES5OdSnF4JDj-kMqEAn1sTm0pQit4wMz30gNCbG6",
        "liveUrl": "https://script.google.com/macros/s/AKfycbxpEmOxlPk1FihbC0SN781hqOSwdBakLevpFdeBneNkxT7T1AEHQjsBU8_R6Fx3ulOT/exec",
        "group": "admin_tools",
        "desc": "Centralized database of all managed assets.",
        "editorUrl": "https://script.google.com/d/1aeyESH70zD4a6_AGES5OdSnF4JDj-kMqEAn1sTm0pQit4wMz30gNCbG6/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Property_Directory",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Property_Directory/PROJECT_MANIFEST.json",
        "migrationStatus": "hub_api_migrated",
        "dataMode": "hub_api",
        "hubTargets": [
            "inventory"
        ],
        "needsApiConversion": false,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Owner_Board_Draft",
        "title": "Owner Specific Dashboard",
        "icon": "📋",
        "scriptId": "1rnQEXxDoEfmkBtZ3_08t36UsIF8BlCB5uBhXXIwdpPA3UEenLkNZH7_v",
        "liveUrl": "https://script.google.com/macros/s/AKfycbzcBbfeXancte7uirmlrSVMkBoZ8fcIePhlVVOOi_MQsWiE_C_gzooqD8FF3cN9xWSZNQ/exec?owner_board=true",
        "group": "financial_audit",
        "desc": "Owner-facing portfolio views and financial snapshots.",
        "testScriptId": "10G6LjCXafowfeh0WDGBjBM92eHc2yCuX4Lk5_5Pv_1BjfX93GD7DUWOf",
        "testEditorUrl": "https://script.google.com/d/10G6LjCXafowfeh0WDGBjBM92eHc2yCuX4Lk5_5Pv_1BjfX93GD7DUWOf/edit",
        "testLiveUrl": "https://script.google.com/macros/s/AKfycbwZHd6t9lp6wTBy_ivrNwYvKv1VnPawHqj_2HSLMRqzfHO4fjgABQkTb3I8N6erSMUD/exec",
        "testStatus": "Exists",
        "editorUrl": "https://script.google.com/d/1rnQEXxDoEfmkBtZ3_08t36UsIF8BlCB5uBhXXIwdpPA3UEenLkNZH7_v/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Owner_Board_Draft",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Owner_Board_Draft/PROJECT_MANIFEST.json",
        "migrationStatus": "legacy_csv_or_drive_data_needs_conversion",
        "dataMode": "legacy_csv_email_or_drive",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Key_Keeper",
        "title": "Key Keeper 2000",
        "icon": "🔐",
        "scriptId": "1Bm4bz3w0jyhHzJGk6wJ7QWgQAfeh78LifjU2G9pxZftsOhR_8584vdaY",
        "liveUrl": "https://script.google.com/macros/s/AKfycbwvwKt7l0VA4WBD85_iGo2NCFnkVeEmwvCBQwRvPc0dcKFS8K1wyT80ST7OPgoCY1Et/exec",
        "group": "admin_tools",
        "desc": "Key inventory and checkout management system.",
        "editorUrl": "https://script.google.com/d/1Bm4bz3w0jyhHzJGk6wJ7QWgQAfeh78LifjU2G9pxZftsOhR_8584vdaY/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Key_Keeper",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Key_Keeper/PROJECT_MANIFEST.json",
        "migrationStatus": "hub_api_migrated",
        "dataMode": "hub_api",
        "hubTargets": [
            "properties",
            "keys_to_be_confirmed"
        ],
        "needsApiConversion": false,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Team_Portal_GAS",
        "title": "Team Portal",
        "icon": "🎯",
        "scriptId": "1Z0jmLeK32JEJ9oPcsuTNZj1FJebqOujekdM2BRV5RHMKzmWLRw2hU2Uj",
        "liveUrl": "https://script.google.com/macros/s/AKfycbwpQPAKBmfxlJ-fMzcFyYoxIR57VY7Cbn1QnOADOOcdv2NN0Sz5cuEQzvC7XoC1JOng/exec",
        "group": "core_ops",
        "desc": "Unified entry point for all internal field operations.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/1Z0jmLeK32JEJ9oPcsuTNZj1FJebqOujekdM2BRV5RHMKzmWLRw2hU2Uj/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Team_Portal_GAS",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Team_Portal_GAS/PROJECT_MANIFEST.json",
        "migrationStatus": "needs_inventory",
        "dataMode": "unknown",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Unbilled_Fee_Audit",
        "title": "Leasing Fee Audit",
        "icon": "📊",
        "scriptId": "1CyQLPxltgr5IE_QbQKez8XP29PfnGUhkek4GoQmw30gNouNilUZS8WHj",
        "liveUrl": "https://script.google.com/macros/s/AKfycbyzLRh_NTcGJwQsY4If9raiL6j5tSY5Z4KZ_fP4JwU31i0wqp5qy8cR3-9JT7SidmZcQw/exec",
        "group": "financial_audit",
        "desc": "Audit engine for identifying missing leasing fees.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/1CyQLPxltgr5IE_QbQKez8XP29PfnGUhkek4GoQmw30gNouNilUZS8WHj/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Unbilled_Fee_Audit",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Unbilled_Fee_Audit/PROJECT_MANIFEST.json",
        "migrationStatus": "legacy_csv_or_drive_data_needs_conversion",
        "dataMode": "legacy_csv_email_or_drive",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Demand_Generator",
        "title": "Demand Generator",
        "icon": "📨",
        "scriptId": "1BNhn9j-06yzQwfsv7PXweWdsxj34FlSnYpNSeA54EtG_FRPmErlrd1ZE",
        "liveUrl": "https://script.google.com/macros/s/AKfycbwVjS2wMi6N1KkC4onYy3Hi4OrES0vwC1yCqShN1nx4gfPPClhR1g4w6OEjmTH-BHA6/exec",
        "group": "admin_tools",
        "desc": "Automated generation of legal demand notices.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/1BNhn9j-06yzQwfsv7PXweWdsxj34FlSnYpNSeA54EtG_FRPmErlrd1ZE/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Demand_Generator",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Demand_Generator/PROJECT_MANIFEST.json",
        "migrationStatus": "legacy_csv_or_drive_data_needs_conversion",
        "dataMode": "legacy_csv_email_or_drive",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Key_Lookup_Tool",
        "title": "Key Lookup Tool",
        "icon": "🔑",
        "scriptId": "1S2l8tbMBOsdWmlM4hYmL-MWtkMlrgYqnPTcfKU6sdfdSIWcIiSbmspxY",
        "liveUrl": "https://script.google.com/macros/s/AKfycbxTEB0brAZ8mcePUQJLHiUotFshC6JKTPLDvQu--pp5aN1R58eUhhIKbIV7KP36A7eM/exec",
        "group": "admin_tools",
        "desc": "Quick read-only lookup for key assignments.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/1S2l8tbMBOsdWmlM4hYmL-MWtkMlrgYqnPTcfKU6sdfdSIWcIiSbmspxY/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Key_Lookup_Tool",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Key_Lookup_Tool/PROJECT_MANIFEST.json",
        "migrationStatus": "legacy_csv_or_drive_data_needs_conversion",
        "dataMode": "legacy_csv_email_or_drive",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Ice_Breakers",
        "title": "Ice Breakers",
        "icon": "❄️",
        "scriptId": "1Yrp_TI9ldAILKZG7id9GM7SM63nuI_KsCeXjvpEuHqe6QD2fv4HF6tsb",
        "liveUrl": "file:///Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My%20Drive/_ACTIVE_PROJECTS/_ACTIVE_PROJECTS/_GOVERNANCE_BACKUPS/LIVE_BACKUPS/2026-05-10_FULL_TEST_220341/AppsScript/Ice_Breakers/index.html",
        "group": "admin_tools",
        "desc": "Automated ice-breaking communication for cold leads.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/1Yrp_TI9ldAILKZG7id9GM7SM63nuI_KsCeXjvpEuHqe6QD2fv4HF6tsb/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/_ACTIVE_PROJECTS/_ACTIVE_PROJECTS/_GOVERNANCE_BACKUPS/LIVE_BACKUPS/2026-05-10_FULL_TEST_220341/AppsScript/Ice_Breakers/index.html",
        "manifestLocalPath": "/Users/richgreen/Dev/PA-Registry-DEV-Workspaces/ice-breakers/registry.json",
        "migrationStatus": "needs_inventory",
        "dataMode": "unknown",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Fitz_Make_Ready_Webapp",
        "title": "Fitz Make Ready Board",
        "icon": "🧹",
        "scriptId": "1RjbHmVyFIi4HGre-1dVMBmA9Pvb6ZUdO8iMz_Byawbi-mgZN-YUE34iQ",
        "liveUrl": "https://script.google.com/macros/s/AKfycbzo6QsZtbbN_F15I3pkt9dSGL9rFRP1S6HKSuTDuuH6CLAMCLtK3C8Cl_vQeiOJVeh7/exec",
        "group": "field_ops",
        "desc": "Cleanliness and turnover tracker for Fitz territory.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/1RjbHmVyFIi4HGre-1dVMBmA9Pvb6ZUdO8iMz_Byawbi-mgZN-YUE34iQ/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Fitz_Make_Ready_Webapp",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Fitz_Make_Ready_Webapp/PROJECT_MANIFEST.json",
        "migrationStatus": "hub_api_migrated",
        "dataMode": "hub_api",
        "hubTargets": [
            "vacancies",
            "moveouts",
            "inspections",
            "workorders"
        ],
        "needsApiConversion": false,
        "credentialReviewNeeded": true,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "guest-card-reporting",
        "title": "Prospect Communication Dashboard",
        "icon": "💬",
        "scriptId": "1vGLgugHLD7GRwFJFB-0zbCrKJCpmJJTvhNuO4wl9MLYAvlBBZCwFZ9wE",
        "liveUrl": "https://script.google.com/a/macros/propalliance.com/s/AKfycby8omixzEndq_yb5ujtWqBdGfJn0gssSJZhdfaYp7PQAE6eIXfcxj_TwV3jYmY2rxYd4Q/exec",
        "group": "admin_tools",
        "desc": "Supervisor dashboard for lead response tracking.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/1vGLgugHLD7GRwFJFB-0zbCrKJCpmJJTvhNuO4wl9MLYAvlBBZCwFZ9wE/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/guest-card-reporting",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/guest-card-reporting/PROJECT_MANIFEST.json",
        "migrationStatus": "gmail_csv_needs_conversion",
        "dataMode": "legacy_csv_email_or_drive",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "AI_Command_Center",
        "title": "AI Command Center",
        "icon": "🤖",
        "scriptId": "1BMdFWTuDCiblXH-QeDTAeylQvMLyFQZkTUKH-wuuCe3dFdARfwsM5vYF",
        "liveUrl": "https://script.google.com/a/macros/propalliance.com/s/AKfycbxyXYNpMtlVlVQCdrDzwxADbyWoWkfzuNlito7e75E-9-ThpAR4dHi7JJDtH1Z37TSi/exec",
        "group": "admin_tools",
        "desc": "Beta: Local AI engine and project brain.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/1BMdFWTuDCiblXH-QeDTAeylQvMLyFQZkTUKH-wuuCe3dFdARfwsM5vYF/edit",
        "devScriptUrl": "https://script.google.com/d/1BMdFWTuDCiblXH-QeDTAeylQvMLyFQZkTUKH-wuuCe3dFdARfwsM5vYF/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/AI_Command_Center",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/AI_Command_Center/PROJECT_MANIFEST.json",
        "migrationStatus": "dev_added_to_registry",
        "dataMode": "local_ai_admin_reference",
        "hubTargets": [],
        "needsApiConversion": false,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Check_Auditor",
        "title": "Check Auditor",
        "icon": "🕵️",
        "scriptId": null,
        "liveUrl": null,
        "group": "financial_audit",
        "desc": "Heuristic auditor for identifying fraudulent checks.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Check_Auditor",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Check_Auditor/PROJECT_MANIFEST.json",
        "migrationStatus": "legacy_csv_or_drive_data_needs_conversion",
        "dataMode": "legacy_csv_email_or_drive",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Reimbursement_Review",
        "title": "Reimbursement Review",
        "icon": "💸",
        "scriptId": null,
        "liveUrl": null,
        "group": "financial_audit",
        "desc": "Tool for auditing resident reimbursement requests.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Reimbursement_Review",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Reimbursement_Review/PROJECT_MANIFEST.json",
        "migrationStatus": "legacy_csv_or_drive_data_needs_conversion",
        "dataMode": "legacy_csv_email_or_drive",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": true,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "Utility_Tracker",
        "title": "Utility Tracker (Legacy)",
        "icon": "☁️",
        "scriptId": "1THz90W4EovYZoWET9wR3BCTaKGfvg9gsyWRGBnoXvjHI-q_3ReyKu4Ux",
        "liveUrl": null,
        "group": "legacy_engine",
        "desc": "Legacy utility management spreadsheet.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/1THz90W4EovYZoWET9wR3BCTaKGfvg9gsyWRGBnoXvjHI-q_3ReyKu4Ux/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Utility_Tracker",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/Utility_Tracker/PROJECT_MANIFEST.json",
        "migrationStatus": "legacy_csv_or_drive_data_needs_conversion",
        "dataMode": "legacy_csv_email_or_drive",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": true,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
    {
        "id": "sandbox-hub",
        "title": "Sandbox Hub",
        "icon": "🧪",
        "scriptId": "1uH0rX5pG5CebunA1R0S7c9E834L7K9m_5D2t1-z9GfS8F7HkQ7z6j4l6",
        "liveUrl": "https://script.google.com/a/macros/propalliance.com/s/AKfycbyD4-JTJsOyceMJTA3Ppy5RIZBGqxC05GxYoAXnXiNhnpyW0UFN8YjXHFLPDgpS59Tf6Q/exec",
        "group": "admin_tools",
        "desc": "Development environment for testing new features and integrations.",
        "lastDataUpdate": null,
        "sourceEmailTime": null,
        "lastCodePush": null,
        "editorUrl": "https://script.google.com/d/1uH0rX5pG5CebunA1R0S7c9E834L7K9m_5D2t1-z9GfS8F7HkQ7z6j4l6/edit",
        "driveFolderLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/sandbox-hub",
        "manifestLocalPath": "/Users/richgreen/Library/CloudStorage/GoogleDrive-rich@propalliance.com/My Drive/PropAlliance_OFFICIAL/Projects/sandbox-hub/PROJECT_MANIFEST.json",
        "migrationStatus": "needs_inventory",
        "dataMode": "unknown",
        "hubTargets": [],
        "needsApiConversion": true,
        "credentialReviewNeeded": false,
        "lastMigrationInventoryUpdate": "2026-04-28T19:58:29"
    },
{
    "id": "Property_Alliance_Collections_Dashboard",
    "title": "Property Alliance Collections Dashboard",
    "icon": "\ud83d\udcc4",
    "scriptId": "1rC2-xlzju5zSPv1X3SoDWUBw07ONmqz_0CNYsU3VsaX6fkg-OzuGbNcY",
    "liveUrl": "https://script.google.com/a/macros/propalliance.com/s/AKfycbyXA_q9q-YkxmoVHmqQwa_dLOMQdWedHJfHZyXLdARZ6a9vgeFU2FtsiCDoFsQmnWIi/exec",
    "group": "core_operations",
    "desc": "Former tenant debt collections workflow dashboard.",
    "lastDataUpdate": null,
    "sourceEmailTime": null,
    "lastCodePush": "2026-05-27",
    "editorUrl": "https://script.google.com/home/projects/1rC2-xlzju5zSPv1X3SoDWUBw07ONmqz_0CNYsU3VsaX6fkg-OzuGbNcY/edit",
    "driveFolderLocalPath": "",
    "manifestLocalPath": "/Users/richgreen/Dev/PA-Registry-DEV-Workspaces/property-alliance-collections-dashboard/registry.json",
    "migrationStatus": "registered_live_app",
    "dataMode": "appfolio_api_reports",
    "hubTargets": [],
    "needsApiConversion": false,
    "credentialReviewNeeded": false,
    "lastMigrationInventoryUpdate": "2026-05-27T00:00:00"
}
];
}
